-- 코드를 입력하세요

SELECT USER.USER_ID, USER.NICKNAME, SUM(BOARD.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as BOARD
JOIN USED_GOODS_USER as USER
ON BOARD.WRITER_ID = USER.USER_ID
WHERE BOARD.STATUS = 'DONE'
GROUP BY BOARD.WRITER_ID
HAVING SUM(BOARD.PRICE) >= 700000
ORDER BY 3
